// VENDORED FROM DeploySignal main@5a72371 — 2026-05-16
// Source: deploysignal/engine/types/agent.ts
// Sync policy: vendored-at-pin
// Extract target: @johnpatrickwarren-oss/deploysignal-engine (Tessera Phase 2 close commitment)
// DO NOT modify internals without ADR; deltas only at architecturally-anchored extension points (see SCOPING-MEMO-v0.3 § 9).

// engine/types/agent.ts — Addition #27 agent configuration + audit
// artifacts. Structural interfaces only; the real AgentProposer class
// lives at advisory/agent/proposer.ts (advisory layer is outside
// engine/ rootDir per R4 2026-04-22).

/** Addition #27 (REPLY-49 D1/D3/D5) — agent configuration. Schema
 *  validates `auto_execute_enabled: false` strictly in v1; v2+
 *  narrow-auto gate is deferred per D3.
 *
 *  Default when `agent` is absent from CompilerOptions: disabled.
 *  Legacy (pre-#27) compiles continue without agent integration. */
export interface ConfiguredAgent {
  /** When false (default), agent path never invoked. Orchestrator
   *  preserves pre-#27 behavior exactly. */
  enabled: boolean;
  /** FM vendor selector per D1. `'stub'` returns scripted responses
   *  for tests + v1 acceptance; real Mosaic-native and Claude-via-
   *  Bedrock wiring is deferred per D5. */
  fm_vendor: 'mosaic_native' | 'claude_bedrock' | 'stub';
  /** Directory holding playbook YAML files. Default `'playbooks/'`. */
  playbook_dir: string;
  /** Rail (c) threshold on FM-self-reported confidence. Proposals
   *  below this threshold downgrade to evidence-only. Default 0.7
   *  per P1 derivation (30% wrong-top-1 operator tolerance). */
  confidence_threshold: number;
  /** Rail (g) — 1 proposal per VerdictGroup.group_id. Default true;
   *  only in-test fixtures flip to false for exercising rate-limit
   *  absence paths. */
  rate_limit_per_incident: boolean;
  /** D3 HARDCODED FALSE in v1. Schema-enforced. Narrow-auto gate
   *  is deferred (documented: "shadow-mode period + <5% reject
   *  rate + operator opt-in"). */
  auto_execute_enabled: false;
}

/** Addition #27 (REPLY-49 D4) — FM-output artifact audited post-
 *  rail evaluation. Strict machine-parseable fields + optional
 *  free-text `human_summary` for oncall at-a-glance consumption. */
export interface ProposedAction {
  /** Must match a loaded playbook entry's `id` (rail a). */
  proposed_action_id: string;
  playbook_category: 'rollback' | 'pause' | 'suppress' | 'scale' | 'widen_budget';
  cited_evidence: {
    /** VerdictGroup.group_id (from #25). */
    cited_verdict_group_id: string;
    /** Optional enrichment provenance from #26 VerdictGroupWithTopology. */
    cited_topology_candidate_ids?: string[];
    /** Addition #5 reversibility tag at proposal time. */
    cited_reversibility: 'reversible' | 'forward_only' | 'conditional';
    cited_firing_families: Array<'A' | 'B' | 'C' | 'D' | 'E'>;
    cited_alpha_consumed_per_family: Partial<Record<'A' | 'B' | 'C' | 'D' | 'E', number>>;
    cited_cell_keys: string[];
  };
  /** FM-self-reported confidence ∈ [0, 1]. Rail (c) gates against
   *  `ConfiguredAgent.confidence_threshold`. */
  confidence: number;
  /** Oncall-facing natural-language summary generated by the FM. */
  human_summary: string;
  /** Templated orchestrator action string from the playbook entry. */
  orchestrator_command: string;
  /** Rail names that passed evaluation for this proposal. Always
   *  a subset of `{ 'a', 'b', 'c', 'd', 'e', 'f', 'g' }`. */
  rails_passed: Array<'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g'>;
}

// ── Consolidated activation slice — structural interfaces ─────────
//
// The real implementations live in advisory/agent/. Engine only sees
// these narrow shapes, avoiding a cross-rootDir import. The actual
// types in advisory/agent/types.ts structurally satisfy these;
// assignment is automatic.

/** Minimal AgentInputContext shape consumed by the orchestrator. */
export interface AgentInputContextLike {
  verdict_group: import('./verdict').VerdictGroup;
  verdict_group_with_topology?: import('./verdict').VerdictGroupWithTopology;
  reversibility_classification: import('./policy').ReversibilityClassification;
  playbook_candidates: ReadonlyArray<unknown>;
  service_metadata?: Record<string, string>;
}

/** Minimal ProposedAction shape the orchestrator reads on
 *  `agent_proposal.emitted` lifecycle emission. */
export interface AgentProposalLike {
  proposed_action_id: string;
  playbook_category: string;
  confidence: number;
}

/** Minimal AgentResult shape returned by AgentProposer.propose(). */
export interface AgentResultLike {
  proposal: AgentProposalLike | null;
  downgraded_to_evidence_only: boolean;
  rails_failed: ReadonlyArray<string>;
  downgrade_reason?: string;
}

/** Minimal AgentProposer shape the orchestrator invokes. */
export interface AgentProposerLike {
  propose(ctx: AgentInputContextLike): Promise<AgentResultLike>;
}
