#!/usr/bin/env bash
# Q-R79-EMPIRICAL.sh — binding-command harness for R79.
#
# Verifies the AC-bound observables (AC-R79-12, -13, -14 directly bind blocks
# of this script; the other ACs are structural and verified by node --test).
# Exit 0 = all blocks pass. Exit non-zero = at least one block failed; failing
# block's diagnostic emitted to stdout.
#
# Invoked by Implementer at chore-A pre-commit AND by Reviewer at audit. Re-
# invokable at any HEAD >= chore-A.
#
# R77 lesson absorbed: Block 3 uses `node --test --test-reporter=tap` so the
# TAP summary lines (`# pass`, `# fail`) can be grepped reliably.
#
# R75 lesson absorbed: no `local` keywords at top level (all variables are
# plain assignments).

set -uo pipefail

ROUND_START_SHA="c87bdfe"
EXIT=0

echo "── Q-R79-EMPIRICAL.sh @ HEAD=$(git rev-parse --short HEAD)"
echo ""

# ── Block 1: typecheck exit code (AC-R79-12 binds presence of this block) ──
echo "── Block 1: typecheck"
pnpm exec tsc -p tsconfig.test.json > /tmp/r79-block1.txt 2>&1
TSC_EXIT=$?
if [ "$TSC_EXIT" -ne 0 ]; then
  echo "Block 1 FAIL: pnpm exec tsc -p tsconfig.test.json exited $TSC_EXIT (expected 0)"
  tail -10 /tmp/r79-block1.txt
  EXIT=1
else
  echo "Block 1 PASS: tsc exit 0"
fi
echo ""

# ── Block 2: required artifact existence (4 R79 artifacts) ──
echo "── Block 2: required artifact existence"
MISSING=""
for F in \
  coordination/specs/Q-R79-SPEC.md \
  coordination/specs/Q-R79-SPEC-AUDIT.md \
  coordination/specs/Q-R79-EMPIRICAL.sh \
  test/q79-dashboard-structure.test.ts; do
  if [ ! -f "$F" ]; then
    MISSING="$MISSING $F"
  fi
done
# Implementer-deliverable artifacts (regenerated by build tool) — required at chore-A
for F in \
  demos/demo.html \
  demos/scenarios/clean-baseline.json \
  demos/scenarios/sdc-drift.json \
  demos/scenarios/common-mode-rack.json \
  demos/scenarios/event-conditional.json \
  demos/scenarios/fdr-multiple-testing.json \
  demos/scenarios/hierarchical-evalue.json \
  demos/scenarios/sparse-data-resilience.json \
  demos/scenarios/topology-spanning-common-mode.json \
  tools/build-canned-demos.ts; do
  if [ ! -f "$F" ]; then
    MISSING="$MISSING $F"
  fi
done
if [ -n "$MISSING" ]; then
  echo "Block 2 FAIL: missing required artifact(s):$MISSING"
  EXIT=1
else
  echo "Block 2 PASS: all 14 required artifacts present"
fi
echo ""

# ── Block 3: test pass/fail counts (R77 lesson: --test-reporter=tap; AC-R79-13 binds presence) ──
echo "── Block 3: test counts"
pnpm exec node --test --test-reporter=tap test/*.test.js > /tmp/r79-block3.txt 2>&1
TEST_EXIT=$?
TEST_PASS=$(grep -E "^# pass " /tmp/r79-block3.txt | head -1 | awk '{print $3}')
TEST_FAIL=$(grep -E "^# fail " /tmp/r79-block3.txt | head -1 | awk '{print $3}')
TEST_TESTS=$(grep -E "^# tests " /tmp/r79-block3.txt | head -1 | awk '{print $3}')
TEST_SUITES=$(grep -E "^# suites " /tmp/r79-block3.txt | head -1 | awk '{print $3}')
TEST_SKIPPED=$(grep -E "^# skipped " /tmp/r79-block3.txt | head -1 | awk '{print $3}')
# Predicted at chore-A: pass = 570 + 14 - 1 (AC-R78-14 flip) = 583; allow ±2 margin → [581, 585].
# fail = 6 + 1 (AC-R78-14 flip) = 7 exact.
EXPECTED_PASS_MIN=581
EXPECTED_PASS_MAX=585
EXPECTED_FAIL=7
if [ -z "$TEST_FAIL" ] || [ "$TEST_FAIL" != "$EXPECTED_FAIL" ]; then
  echo "Block 3 FAIL: fail count = '${TEST_FAIL:-<empty>}'; expected $EXPECTED_FAIL (carry-forward 6 + AC-R78-14 forward-protection flip = 7)"
  echo "  TAP tail:"
  tail -20 /tmp/r79-block3.txt
  EXIT=1
elif [ -z "$TEST_PASS" ] || [ "$TEST_PASS" -lt "$EXPECTED_PASS_MIN" ] || [ "$TEST_PASS" -gt "$EXPECTED_PASS_MAX" ]; then
  echo "Block 3 FAIL: pass count = '${TEST_PASS:-<empty>}'; expected in [$EXPECTED_PASS_MIN, $EXPECTED_PASS_MAX] (570 + 14 - 1 ± 2)"
  echo "  TAP tail:"
  tail -20 /tmp/r79-block3.txt
  EXIT=1
else
  echo "Block 3 PASS: tests=$TEST_TESTS suites=$TEST_SUITES pass=$TEST_PASS fail=$TEST_FAIL skipped=$TEST_SKIPPED"
fi
echo ""

# ── Block 4: anti-scope diff ⊆ ALLOWED_SET (AC-R79-14) ──
echo "── Block 4: anti-scope diff"
DIFF_FILES=$(git diff "$ROUND_START_SHA" HEAD --name-only)
ALLOWED='^(demos/demo\.html|demos/scenarios/[a-z-]+\.json|tools/build-canned-demos\.ts|package\.json|README\.md|test/q79-dashboard-structure\.test\.ts|coordination/specs/Q-R79-SPEC\.md|coordination/specs/Q-R79-SPEC-AUDIT\.md|coordination/specs/Q-R79-EMPIRICAL\.sh|coordination/NEXT-ROLE\.md|coordination/MEMORIAL\.md|coordination/MEMORIAL-PHASE-[0-9]+\.md|coordination/reviews/REVIEWER-REPORT-R79\.md|coordination/logs/ROUND-R[0-9]+-(SUMMARY|ROUTING)\.md|coordination/diagnostics/DIAGNOSTIC-R[0-9]+-.*\.md|CLAUDE\.md|CLAUDE-ARCHITECT\.md|CLAUDE-IMPLEMENTER\.md|CLAUDE-REVIEWER\.md|CLAUDE-MEMORIAL\.md|CLAUDE-COMMON\.md|CLAUDE-COORDINATOR\.md)$'
UNAUTHORIZED=$(echo "$DIFF_FILES" | grep -vE "$ALLOWED" || true)
UNAUTHORIZED=$(echo "$UNAUTHORIZED" | sed '/^[[:space:]]*$/d')
if [ -n "$UNAUTHORIZED" ]; then
  echo "Block 4 FAIL: unauthorized paths in round-start..HEAD diff:"
  echo "$UNAUTHORIZED"
  EXIT=1
else
  TOTAL_DIFF_COUNT=$(echo "$DIFF_FILES" | sed '/^[[:space:]]*$/d' | wc -l | tr -d ' ')
  echo "Block 4 PASS: $TOTAL_DIFF_COUNT files in diff, all within ALLOWED_SET"
fi
echo ""

# ── Summary ──
if [ "$EXIT" -eq 0 ]; then
  echo "── Q-R79-EMPIRICAL.sh: ALL BLOCKS PASS"
else
  echo "── Q-R79-EMPIRICAL.sh: AT LEAST ONE BLOCK FAILED (exit $EXIT)"
fi
exit "$EXIT"
