#!/usr/bin/env bash
# Q-R81-EMPIRICAL.sh — binding-command harness for R81.
#
# Verifies the AC-bound observables (AC-R81-13 directly binds presence of
# Blocks 1, 3, 4; AC-R81-14 mirrors Block 4 anti-scope check; the structural
# R81 ACs are verified by node --test).
# Exit 0 = all blocks pass. Exit non-zero = at least one block failed;
# failing block's diagnostic emitted to stdout.
#
# Invoked by Architect at spec-emit time (probe-run; expected exit 1 at
# round-start HEAD because Implementer artifacts absent — Q-R81-SPEC-AUDIT.md
# § C.3 records the verbatim probe-run output).
# Invoked by Implementer at chore-A pre-commit (expected exit 0).
# Invoked by Reviewer at audit (expected exit 0).
# Re-invokable at any HEAD >= chore-A.
#
# Cross-project rule discipline:
#   - R77 lesson: Block 3 uses `node --test --test-reporter=tap` so the
#     TAP summary lines (`# pass`, `# fail`) can be grepped reliably.
#   - R75 lesson: no `local` keywords at top level (all variables are
#     plain assignments).
#   - R79 MAJOR-1 lesson: encode actual observed values verbatim; do NOT
#     pre-amend EXPECTED_FAIL to absorb un-predicted flips. If the actual
#     `# fail` differs from `EXPECTED_FAIL`, HALT + write DIAGNOSTIC.
#   - R73 MAJOR-2 lesson: no control-flow rewrites; Implementer is forbidden
#     from rewriting `if [...]; then` blocks to `case` (or vice versa). The
#     EMPIRICAL.sh control-flow shape is part of the spec triad; deviations
#     are halt conditions.

set -uo pipefail

ROUND_START_SHA="0eb371f"
EXIT=0

echo "── Q-R81-EMPIRICAL.sh @ HEAD=$(git rev-parse --short HEAD)"
echo ""

# ── Block 1: typecheck exit code (AC-R81-13 binds presence of this block) ──
echo "── Block 1: typecheck"
pnpm exec tsc -p tsconfig.test.json > /tmp/r81-block1.txt 2>&1
TSC_EXIT=$?
if [ "$TSC_EXIT" -ne 0 ]; then
  echo "Block 1 FAIL: pnpm exec tsc -p tsconfig.test.json exited $TSC_EXIT (expected 0)"
  tail -10 /tmp/r81-block1.txt
  EXIT=1
else
  echo "Block 1 PASS: tsc exit 0"
fi
echo ""

# ── Block 2: required artifact existence (15 R81 artifacts) ──
echo "── Block 2: required artifact existence"
MISSING=""
for F in \
  coordination/specs/Q-R81-SPEC.md \
  coordination/specs/Q-R81-SPEC-AUDIT.md \
  coordination/specs/Q-R81-EMPIRICAL.sh \
  test/q81-slice-2-close.test.ts \
  demos/DEMO-SCRIPT.md; do
  if [ ! -f "$F" ]; then
    MISSING="$MISSING $F"
  fi
done
# Implementer-deliverable artifacts (regenerated by build tool) — required at chore-A
for F in \
  demos/demo.html \
  demos/scenarios/clean-baseline.json \
  demos/scenarios/sdc-drift.json \
  demos/scenarios/common-mode-rack.json \
  demos/scenarios/event-conditional.json \
  demos/scenarios/fdr-multiple-testing.json \
  demos/scenarios/hierarchical-evalue.json \
  demos/scenarios/sparse-data-resilience.json \
  demos/scenarios/topology-spanning-common-mode.json \
  tools/build-canned-demos.ts; do
  if [ ! -f "$F" ]; then
    MISSING="$MISSING $F"
  fi
done
if [ -n "$MISSING" ]; then
  echo "Block 2 FAIL: missing required artifact(s):$MISSING"
  EXIT=1
else
  echo "Block 2 PASS: all 15 required artifacts present"
fi
echo ""

# ── Block 3: test pass/fail counts (R77 lesson: --test-reporter=tap; AC-R81-13 binds presence) ──
echo "── Block 3: test counts"
pnpm exec node --test --test-reporter=tap test/*.test.js > /tmp/r81-block3.txt 2>&1
TEST_EXIT=$?
TEST_PASS=$(grep -E "^# pass " /tmp/r81-block3.txt | head -1 | awk '{print $3}')
TEST_FAIL=$(grep -E "^# fail " /tmp/r81-block3.txt | head -1 | awk '{print $3}')
TEST_TESTS=$(grep -E "^# tests " /tmp/r81-block3.txt | head -1 | awk '{print $3}')
TEST_SUITES=$(grep -E "^# suites " /tmp/r81-block3.txt | head -1 | awk '{print $3}')
TEST_SKIPPED=$(grep -E "^# skipped " /tmp/r81-block3.txt | head -1 | awk '{print $3}')
# Predicted at chore-A:
#   pass = R80-close 594 + 14 new R81 ACs - 1 (AC-R80-14 forward-protection flip) = 607;
#          allow ±2 margin → [605, 609].
#   fail = R80-close 10 + 1 (AC-R80-14 forward-protection flip) = 11.
# AC-R80-14 flip: R80's ALLOWED regex doesn't include R81 paths
#   (test/q81-slice-2-close.test.ts, coordination/specs/Q-R81-*, REVIEWER-REPORT-R81.md,
#   demos/DEMO-SCRIPT.md).
# Carry-forward 10 from R80 close:
#   AC-R36-21 + AC-R36-30 + AC-R36-31 + R65 sibling-dep + R66 sibling-dep
#   + AC-R77-14 + AC-R77-17 + AC-R78-14 + AC-R79-8 + AC-R79-14 = 10.
EXPECTED_PASS_MIN=605
EXPECTED_PASS_MAX=609
EXPECTED_FAIL=11
if [ -z "$TEST_FAIL" ] || [ "$TEST_FAIL" != "$EXPECTED_FAIL" ]; then
  echo "Block 3 FAIL: fail count = '${TEST_FAIL:-<empty>}'; expected $EXPECTED_FAIL (R80-close carry-forward 10 + AC-R80-14 forward-protection flip = 11)"
  echo "  TAP tail:"
  tail -20 /tmp/r81-block3.txt
  EXIT=1
elif [ -z "$TEST_PASS" ] || [ "$TEST_PASS" -lt "$EXPECTED_PASS_MIN" ] || [ "$TEST_PASS" -gt "$EXPECTED_PASS_MAX" ]; then
  echo "Block 3 FAIL: pass count = '${TEST_PASS:-<empty>}'; expected in [$EXPECTED_PASS_MIN, $EXPECTED_PASS_MAX] (594 + 14 - 1 ± 2)"
  echo "  TAP tail:"
  tail -20 /tmp/r81-block3.txt
  EXIT=1
else
  echo "Block 3 PASS: tests=$TEST_TESTS suites=$TEST_SUITES pass=$TEST_PASS fail=$TEST_FAIL skipped=$TEST_SKIPPED"
fi
echo ""

# ── Block 4: anti-scope diff ⊆ ALLOWED_SET (AC-R81-14) ──
echo "── Block 4: anti-scope diff"
DIFF_FILES=$(git diff "$ROUND_START_SHA" HEAD --name-only)
ALLOWED='^(demos/demo\.html|demos/scenarios/[a-z-]+\.json|demos/DEMO-SCRIPT\.md|tools/build-canned-demos\.ts|package\.json|README\.md|test/q81-slice-2-close\.test\.ts|coordination/specs/Q-R81-SPEC\.md|coordination/specs/Q-R81-SPEC-AUDIT\.md|coordination/specs/Q-R81-EMPIRICAL\.sh|coordination/NEXT-ROLE\.md|coordination/MEMORIAL\.md|coordination/MEMORIAL-PHASE-[0-9]+\.md|coordination/reviews/REVIEWER-REPORT-R81\.md|coordination/logs/ROUND-R[0-9]+-(SUMMARY|ROUTING)\.md|coordination/diagnostics/DIAGNOSTIC-R[0-9]+-.*\.md|CLAUDE\.md|CLAUDE-ARCHITECT\.md|CLAUDE-IMPLEMENTER\.md|CLAUDE-REVIEWER\.md|CLAUDE-MEMORIAL\.md|CLAUDE-COMMON\.md|CLAUDE-COORDINATOR\.md)$'
UNAUTHORIZED=$(echo "$DIFF_FILES" | grep -vE "$ALLOWED" || true)
UNAUTHORIZED=$(echo "$UNAUTHORIZED" | sed '/^[[:space:]]*$/d')
if [ -n "$UNAUTHORIZED" ]; then
  echo "Block 4 FAIL: unauthorized paths in round-start..HEAD diff:"
  echo "$UNAUTHORIZED"
  EXIT=1
else
  TOTAL_DIFF_COUNT=$(echo "$DIFF_FILES" | sed '/^[[:space:]]*$/d' | wc -l | tr -d ' ')
  echo "Block 4 PASS: $TOTAL_DIFF_COUNT files in diff, all within ALLOWED_SET"
fi
echo ""

# ── Summary ──
if [ "$EXIT" -eq 0 ]; then
  echo "── Q-R81-EMPIRICAL.sh: ALL BLOCKS PASS"
else
  echo "── Q-R81-EMPIRICAL.sh: AT LEAST ONE BLOCK FAILED (exit $EXIT)"
fi
exit "$EXIT"
