// tools/_coverage-saturation-matrix.ts — Tessera R72 coverage saturation:
// aggregation (summarize/build) + serialization (JSON/Markdown).
//
// Split verbatim out of tools/coverage-saturation.ts (god-file refactor). No
// behavior change; pure relocation.

import {
  SCENARIO_SEED_PREFIX,
  type FailureTypeName,
  type VariationRow,
  type TypeSummary,
  type TypeBlock,
  type CoverageMatrix,
} from './_coverage-saturation-types.js';
import {
  runType1Variation,
  runType2Variation,
  runType3Variation,
  runType4Variation,
  runType5Variation,
  runType6Variation,
} from './_coverage-saturation-variations.js';

// ── Aggregation ──
function summarizeType(type_name: FailureTypeName, rows: VariationRow[]): TypeSummary {
  const detected_rows = rows.filter(r => r.observation.detected);
  const correct_rows = detected_rows.filter(r => r.observation.attribution_correct === true);
  // Rows that MEASURE attribution at all (2026-07-02: a type whose scenario has no localization
  // target reports null for every row — its accuracy must be null/'n/a', not a vacuous 100%).
  const measured_rows = detected_rows.filter(r => r.observation.attribution_correct !== null);
  const fp_values = detected_rows
    .map(r => r.observation.false_positive_count)
    .filter((x): x is number => x !== null);
  const max_fp = fp_values.length > 0 ? Math.max(...fp_values) : null;
  let pedagogical_rate: number | null = null;
  if (type_name === 'hierarchical-evalue') {
    const ped_rows = detected_rows.filter(r => r.observation.pedagogical_property_met === true);
    pedagogical_rate = detected_rows.length > 0 ? ped_rows.length / detected_rows.length : null;
  }
  return {
    detection_rate: detected_rows.length / 20,
    detected_count: detected_rows.length,
    attribution_accuracy: measured_rows.length > 0 ? correct_rows.length / measured_rows.length : null,
    correct_count: correct_rows.length,
    max_false_positive_count: max_fp,
    pedagogical_property_rate: pedagogical_rate,
  };
}

function buildType(type_name: FailureTypeName,
                   description: string,
                   primary_axis_label: string,
                   secondary_axis_label: string,
                   runner: (idx: number) => VariationRow): TypeBlock {
  const variations: VariationRow[] = [];
  for (let i = 0; i < 20; i++) variations.push(runner(i));
  return {
    type_name,
    description,
    primary_axis_label,
    secondary_axis_label,
    variations,
    summary: summarizeType(type_name, variations),
  };
}

export function buildCoverageMatrix(): CoverageMatrix {
  const types: TypeBlock[] = [
    buildType('sdc-drift',
      'Single-shard SDC: linear additive drift on one targeted shard within a 10-shard, 30-window fleet under Family A betting e-process.',
      'target_shard_id', '(drift_per_window, drift_start_window)',
      runType1Variation),
    buildType('common-mode-rack',
      'Rack-localized common-mode: 2 or 3 shards co-fire on the same rack; default attribution opts (max_hop=1, min_member=2).',
      '(target_rack, fired_set)', 'attribution_window',
      runType2Variation),
    buildType('event-conditional',
      'DS deploy-event activates the freeze-hook; subsequent residual update returns the existing residual unchanged (absorbed=false).',
      'event_class', '(event_ts_offset_s, sample_ts_offset_s)',
      runType3Variation),
    buildType('fdr-multiple-testing',
      'e-Benjamini-Hochberg FDR control: K drifting shards in a 10-shard fleet; e-BH selects under qLevel.',
      'drifting_shard_count', 'qLevel',
      runType4Variation),
    buildType('hierarchical-evalue',
      'Hierarchical e-value combination via combineAverage; small uniform drift across all shards; fleet wealth crosses log(1/0.05).',
      'shard_count', '(drift_per_window, drift_start_window)',
      runType5Variation),
    buildType('topology-spanning-common-mode',
      'Cross-rack common-mode: BFS over cooling-zone-spanning topology; max_hop_distance varies to expose the 1-hop / 2-hop reachability boundary.',
      'fired_set', 'max_hop_distance',
      runType6Variation),
  ];
  const total_detected = types.reduce((acc, t) => acc + t.summary.detected_count, 0);
  const total_correct = types.reduce((acc, t) => acc + t.summary.correct_count, 0);
  return {
    schema_version: 'tessera-coverage-v1',
    generated_with_seed_prefix: SCENARIO_SEED_PREFIX,
    types,
    totals: {
      total_variations: 120,
      total_detected,
      total_attribution_correct: total_correct,
    },
  };
}

// ── Serialization ──
export function serializeMatrixJson(matrix: CoverageMatrix): string {
  return JSON.stringify(matrix, null, 2) + '\n';
}

export function renderMatrixMd(matrix: CoverageMatrix): string {
  const lines: string[] = [];
  lines.push('# Tessera R72 — coverage saturation matrix');
  lines.push('');
  lines.push('Generated by `tools/coverage-saturation.ts`; deterministic; idempotent. Full machine-readable data: `R72-saturation-matrix.json`.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Type | detected | attrib-correct | max-FP | pedagogical |');
  lines.push('|---|---|---|---|---|');
  for (const t of matrix.types) {
    const s = t.summary;
    const detect_cell = `${s.detected_count} / 20 (${(s.detection_rate * 100).toFixed(0)}%)`;
    const attrib_cell = s.attribution_accuracy === null
      ? 'n/a'
      : `${s.correct_count} / ${s.detected_count} (${(s.attribution_accuracy * 100).toFixed(0)}%)`;
    const fp_cell = s.max_false_positive_count === null ? 'n/a' : String(s.max_false_positive_count);
    const ped_cell = s.pedagogical_property_rate === null
      ? 'n/a'
      : `${(s.pedagogical_property_rate * 100).toFixed(0)}%`;
    lines.push(`| ${t.type_name} | ${detect_cell} | ${attrib_cell} | ${fp_cell} | ${ped_cell} |`);
  }
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push('| Total variations | Total detected | Total attribution-correct |');
  lines.push('|---|---|---|');
  lines.push(`| ${matrix.totals.total_variations} | ${matrix.totals.total_detected} | ${matrix.totals.total_attribution_correct} |`);
  lines.push('');
  lines.push('## Per-type details');
  lines.push('');
  for (let ti = 0; ti < matrix.types.length; ti++) {
    const t = matrix.types[ti];
    lines.push(`### ${ti + 1}. ${t.type_name}`);
    lines.push('');
    lines.push(t.description);
    lines.push('');
    lines.push(`Primary axis: \`${t.primary_axis_label}\`. Secondary axis: \`${t.secondary_axis_label}\`.`);
    lines.push('');
    lines.push('| idx | params | detected | attrib-correct | det-window | FP-count | pedagogical |');
    lines.push('|---|---|---|---|---|---|---|');
    for (const v of t.variations) {
      const o = v.observation;
      const params_cell = JSON.stringify(v.params);
      const det_cell = o.detected ? 'yes' : 'no';
      const attrib_cell = o.attribution_correct === null ? 'n/a' : (o.attribution_correct ? 'yes' : 'no');
      const win_cell = o.detection_window_index === null ? 'n/a' : String(o.detection_window_index);
      const fp_cell = o.false_positive_count === null ? 'n/a' : String(o.false_positive_count);
      const ped_cell = o.pedagogical_property_met === null ? 'n/a' : (o.pedagogical_property_met ? 'yes' : 'no');
      lines.push(`| ${v.variation_idx} | \`${params_cell.replace(/\|/g, '\\|')}\` | ${det_cell} | ${attrib_cell} | ${win_cell} | ${fp_cell} | ${ped_cell} |`);
    }
    lines.push('');
  }
  lines.push('## Method');
  lines.push('');
  lines.push('Each variation is a deterministic engine run seeded by `(SCENARIO_SEED_PREFIX ^ variation_idx)` (plus per-type-namespace offsets for types 4 and 5 to prevent cross-type seed collisions). The runner imports engine surfaces by `.js` extension (matches existing `tools/` convention); no engine modifications; no new dependencies. Re-running `pnpm coverage` produces byte-identical output.');
  lines.push('');
  return lines.join('\n');
}
