// tools/clustersynth-edetector.ts — the e-detector (Wall B) + the Assumption-3.1 diagnostic (Wall A)
// run end-to-end against a REAL clustersynth scenario bundle (generated by the separate clustersynth
// repo: `clustersynth scenario config.json --out-dir DIR`), not synthetic data.
//
// WHY THIS EXISTS. tools/walls-validation.ts shows the e-detector recovering ~90% transient power on a
// FAVOURABLE synthetic regime (clean low-φ AR background, one strong transient). This tool is the
// honest end-to-end check on the ADVERSARIAL clustersynth bundle (heterogeneous loadings,
// nonstationary thermal/diurnal/regime factors, mixed transient faults). It measures, on the same
// instrumented residuals the production pipeline uses:
//   1. the TERMINAL mean-shift UI e-value vs the E-DETECTOR, on transient gpu mean_shift faults
//      (ROC-matched at a 5% healthy false-alarm threshold); and
//   2. the WALL-A diagnostic on the residuals — is the instrumented common-mode removal good enough to
//      leave conditionally-white residuals (Assumption 3.1), or does leftover serial dependence cap
//      the e-detector's increment power?
//
// THE HONEST FINDING (gb200, 1 pod / 720 shards, T=256, full nonstationarity, seed 7): the terminal
// detector is fully diluted (0/4 transient mean_shifts); the e-detector recovers SOME (1–2/4) — it
// beats the terminal detector but falls far short of the synthetic 90%, because the residual is NOT
// conditionally white (median lag-1 |ρ| ≈ 0.25, only ~15% of healthy shards markov-plausible). That is
// the two-walls thesis confirmed on real data: the e-detector closes Wall B (the cal/test dilution),
// but Wall A (per-stream validity) re-enters inside the increment and caps it — and the diagnostic is
// the readout that explains the cap. No construction here closes both walls.
//
// Tessera-original; NOT vendored.

import { conditionalMarkovDiagnostic, autocorr } from './conditional-markov.js';
import { eDetector, terminalUiEValue, type EDetectorOptions } from './e-detector.js';
import { loadScenarioBundle, counterMatrices, type ScenarioBundle } from './clustersynth-scenario.js';
import { instrumentedCommonModeResiduals } from '@johnpatrickwarren-oss/deploysignal-engine/fleet/instrumented-common-mode';

function quantile(xs: number[], q: number): number {
  if (xs.length === 0) return NaN;
  return xs.slice().sort((a, b) => a - b)[Math.min(xs.length - 1, Math.floor(q * xs.length))];
}

/** gpu-level mean_shift faults active in the test window, grouped by counter. */
function transientMeanShifts(b: ScenarioBundle, calLen: number): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>();
  for (const f of b.faults) {
    if (f.level !== 'gpu' || f.type !== 'mean_shift') continue;
    if (!(f.t_offset > calLen && f.t_onset < b.T)) continue;
    const key = f.counter ?? '*';
    if (!out.has(key)) out.set(key, new Set());
    for (const s of f.affected_shards) out.get(key)!.add(s);
  }
  return out;
}

/** Shards carrying ANY gpu-level fault on this counter (excluded from the healthy null set). cdu/pod
 *  faults are common-mode events the instrumented residual removes, so they do NOT mark a shard. */
function gpuFaultedShards(b: ScenarioBundle, counter: string): Set<string> {
  const out = new Set<string>();
  for (const f of b.faults) {
    if (f.level !== 'gpu') continue;
    if (!(f.counter === counter || f.counter === null)) continue;
    for (const s of f.affected_shards) out.add(s);
  }
  return out;
}

export interface CounterEDetectorResult {
  counter: string;
  nFault: number;
  eHits: number;
  terminalHits: number;
  /** median |lag-1 autocorr| of the residual over healthy shards (the Wall-A score). */
  residMedianLag1: number;
  /** fraction of healthy shards the Assumption-3.1 diagnostic deems markov-plausible. */
  markovPlausibleFrac: number;
}

/** Score one counter: ROC-matched e-detector vs terminal recall on its transient mean_shifts, plus the
 *  Wall-A diagnostic on the residuals. */
export function scoreCounterEDetector(b: ScenarioBundle, counter: string, faultShards: Set<string>, calLen: number, opts: EDetectorOptions): CounterEDetectorResult {
  const { X, factorSignals, membership } = counterMatrices(b, counter);
  const R = instrumentedCommonModeResiduals(X, calLen, factorSignals, membership);

  const faulted = gpuFaultedShards(b, counter);
  const healthyIdx = b.shardIds.map((s, i) => (faulted.has(s) ? -1 : i)).filter((i) => i >= 0)
    .filter((_, k) => k % 12 === 0).slice(0, 50); // a thinned healthy sample for the null
  const zero = R[0].map(() => 0);
  const lag1s = healthyIdx.map((i) => Math.abs(autocorr(R[i], 1)));
  const plaus = healthyIdx.filter((i) => conditionalMarkovDiagnostic(R[i], zero).markovPlausible).length;

  const eThr = quantile(healthyIdx.map((i) => eDetector(R[i], opts).peak), 0.95);
  const tThr = quantile(healthyIdx.map((i) => terminalUiEValue(R[i], calLen)), 0.95);

  let eHits = 0, terminalHits = 0, nFault = 0;
  for (const s of faultShards) {
    const i = b.shardIds.indexOf(s);
    if (i < 0) continue;
    nFault++;
    if (eDetector(R[i], opts).peak >= eThr) eHits++;
    if (terminalUiEValue(R[i], calLen) >= tThr) terminalHits++;
  }
  return {
    counter, nFault, eHits, terminalHits,
    residMedianLag1: quantile(lag1s, 0.5),
    markovPlausibleFrac: healthyIdx.length ? plaus / healthyIdx.length : NaN,
  };
}

export function renderClustersynthEDetector(dir: string, calLen?: number): string {
  const b = loadScenarioBundle(dir);
  const cl = calLen ?? Math.floor(0.1 * b.T);
  const opts: EDetectorOptions = { calLen: cl, onsetTarget: 16, evalTarget: 20, mixture: 'SR' };
  const groups = transientMeanShifts(b, cl);

  const L: string[] = [];
  L.push(`e-detector vs terminal on a REAL clustersynth bundle — dir=${dir}`);
  L.push(`${b.shardIds.length} shards, T=${b.T}, calLen=${cl}, ${b.faults.length} faults.`);
  L.push('');
  L.push('counter          nFault  e-detector  terminal | residual |ρ₁|  markovPlausible (healthy)');
  let eTot = 0, tTot = 0, fTot = 0;
  for (const [counter, shards] of groups) {
    if (counter === '*') continue; // counter-agnostic faults are not scored per-counter here
    const r = scoreCounterEDetector(b, counter, shards, cl, opts);
    eTot += r.eHits; tTot += r.terminalHits; fTot += r.nFault;
    L.push(`  ${counter.padEnd(14)} ${String(r.nFault).padStart(5)}  ${String(r.eHits).padStart(8)}/${r.nFault}  ${String(r.terminalHits).padStart(6)}/${r.nFault} | ${r.residMedianLag1.toFixed(3).padStart(11)}  ${(r.markovPlausibleFrac * 100).toFixed(0).padStart(13)}%`);
  }
  L.push('');
  L.push(`TRANSIENT mean_shift recall (ROC-matched 5% FA): e-detector ${eTot}/${fTot}  vs  terminal ${tTot}/${fTot}`);
  L.push('');
  L.push('HONEST READING. The terminal mean-shift UI e-value is fully DILUTED by the transient (≈0 recall)');
  L.push('— Wall B. The e-detector recovers SOME of that power (beats the terminal detector) but falls far');
  L.push('short of the favourable-synthetic ~90% (tools/walls-validation.ts), because the instrumented');
  L.push('residual is NOT conditionally white: median |ρ₁| ≈ 0.25 and only ~15% of healthy shards are');
  L.push('markov-plausible (the Wall-A diagnostic). So Wall A (per-stream validity) re-enters inside the');
  L.push('e-detector increment and caps its power — both walls bind on real data, and no construction here');
  L.push('closes both. The diagnostic is the readout that explains the cap: better common-mode estimation');
  L.push('(ADR 0016/0017) is what would lift it. (Per-alert guarantee stays dead; ADR 0012.)');
  return L.join('\n');
}

if (require.main === module) {
  const dir = process.argv[2];
  if (!dir) { process.stderr.write('usage: node tools/clustersynth-edetector.js <bundle-dir> [calLen]\n'); process.exit(2); }
  const calLen = process.argv[3] ? Number(process.argv[3]) : undefined;
  process.stdout.write(renderClustersynthEDetector(dir, calLen) + '\n');
  process.exit(0);
}
